Style/Documentation:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: true
  Max: 15
  
Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/IfUnlessModifier: 
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Layout/LineLength:
  Enabled: false