Style/Documentation:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: true
  Max: 15
  
Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false